// Code generation for the extension host side. Most per-operation code lives
// in `src/shared/operations.ts`; this file handles the composition layer —
// turning a list of applied steps into a standalone exportable Python module.

import { getOperation, type OperationSpec } from '../shared/operations';
import type { OperationStep } from '../shared/types';

export function generateStepCode(
  operationId: string,
  parameters: Record<string, unknown>
): { code: string; label: string } {
  const op = getOperation(operationId);
  if (!op) {
    throw new Error(`Unknown operation: ${operationId}`);
  }
  return {
    code: op.generate(parameters),
    label: composeLabel(op, parameters)
  };
}

function composeLabel(op: OperationSpec, params: Record<string, unknown>): string {
  const col = params.column ?? params.columns ?? params.oldName;
  if (col) {
    const name = Array.isArray(col) ? col.join(', ') : String(col);
    return `${op.label}: ${name}`;
  }
  return op.label;
}

export function exportAsNotebookCell(steps: readonly OperationStep[]): string {
  const header = `# Generated by Kensa on ${new Date().toISOString()}`;
  const body = steps
    .map((s, i) => `    # Step ${i + 1}: ${s.label}\n    ${indent(s.code, '    ')}`)
    .join('\n');
  return `${header}\nimport pandas as pd\nimport numpy as np\n\ndef clean_data(df):\n    """Data cleaning steps generated by Kensa."""\n${body || '    pass'}\n    return df\n`;
}

function indent(code: string, prefix: string): string {
  return code
    .split('\n')
    .map((line, i) => (i === 0 ? line : prefix + line))
    .join('\n');
}

export function newStepId(): string {
  return `step-${Date.now().toString(36)}-${Math.floor(Math.random() * 1e6).toString(36)}`;
}
